#!/usr/bin/python


name=input('Name: ')
weight=input('Weight: ')
weight=float(weight)
height= input('Height: ')
height=float(height)
bmi=weight/(height**2)
bmi=round(bmi,2)
print('Hey ' ,name)
print('Your BMI is ' ,bmi)
