#!/usr/bin/python


name=input('Name: ')
weight=input('Weight: ')
weight=float(weight)
height= input('Height: ')
height=float(height)
bmi=weight/(height**2)
bmi=round(bmi,2)
print('Hey ' ,name)
print('Your BMI is ' ,bmi)

if bmi>=25:
    print('Your weight is too high')
elif bmi<18.5:
    print('your weight is too low')
else:
    print('your weight is normal')
print('End of Programm')
